### ISSUE TITLE
希望补充一下文档或者示例，我想设置缩放比例，还有自定义列表

### ISSUE THREAD

**Issue by suyie001** [pdliuw/ai_amap#2]
希望补充一下文档或者示例，我想设置缩放比例，还有自定义列表

**Comment by suyie001** [comment]
还有如果只要个定位，不需要地图的话怎么做呢？跟其他amap插件冲突

**Comment by pdliuw** [comment]
> 还有如果只要个定位，不需要地图的话怎么做呢？跟其他amap插件冲突

不需要展示地图，只需单个定位功能现已开放：[定位服务核心功能](https://github.com/pdliuw/ai_amap#2%E4%BD%BF%E7%94%A8%E5%AE%9A%E4%BD%8D%E6%9C%8D%E5%8A%A1%E7%9A%84%E5%9C%B0%E6%96%B9%E4%B8%AD)
