### ISSUE TITLE
关于1.1.0 IOS 提示 type 'AiAMapLocationPlatformView' does not conform to protocol 'AMapGeoFenceManagerDelegate'

### ISSUE THREAD

**Issue by zzg19901210** [pdliuw/ai_amap#3]
日志如下： 
/Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: error: type 'AiAMapLocationPlatformView' does not conform to protocol 'AMapGeoFenceManagerDelegate'
    class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
          ^
    /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: note: do you want to add protocol stubs?
    class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
          ^
    /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:231:46: warning: forced cast from 'String??' to 'String' only unwraps optionals; did you mean to use '!!'?
                    naviTitle = annotation.title as! String;
                                ~~~~~~~~~~~~~~~~~^~~~~~~~~~
                                                !!

**Comment by pdliuw** [comment]
> 日志如下：
> /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: error: type 'AiAMapLocationPlatformView' does not conform to protocol 'AMapGeoFenceManagerDelegate'
> class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
> ^
> /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: note: do you want to add protocol stubs?
> class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
> ^
> /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:231:46: warning: forced cast from 'String??' to 'String' only unwraps optionals; did you mean to use '!!'?
> naviTitle = annotation.title as! String;
> ~~~~~~~~~~~~~~~~~^~~~~~~~~~
> !!

may be because of swift version difference...
what's your version about swift develop language?

**Comment by zzg19901210** [comment]
我的语言采用 OC 来编辑

**Comment by zzg19901210** [comment]
> > 日志如下：
> > /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: error: type 'AiAMapLocationPlatformView' does not conform to protocol 'AMapGeoFenceManagerDelegate'
> > class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
> > ^
> > /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: note: do you want to add protocol stubs?
> > class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
> > ^
> > /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:231:46: warning: forced cast from 'String??' to 'String' only unwraps optionals; did you mean to use '!!'?
> > naviTitle = annotation.title as! String;
> > ```
> > !!
> > ```
> 
> may be because of swift version difference...
> what's your version about swift develop language?

开发语言采用OC

**Comment by pdliuw** [comment]
> > > 日志如下：
> > > /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: error: type 'AiAMapLocationPlatformView' does not conform to protocol 'AMapGeoFenceManagerDelegate'
> > > class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
> > > ^
> > > /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:17:7: note: do you want to add protocol stubs?
> > > class AiAMapLocationPlatformView:NSObject,FlutterPlatformView,MAMapViewDelegate, AMapLocationManagerDelegate,AMapGeoFenceManagerDelegate,AMapNaviCompositeManagerDelegate{
> > > ^
> > > /Users/zhangzhigang/.pub-cache/hosted/pub.flutter-io.cn/ai_amap-1.1.0/ios/Classes/AiAMapLocationPlatformView.swift:231:46: warning: forced cast from 'String??' to 'String' only unwraps optionals; did you mean to use '!!'?
> > > naviTitle = annotation.title as! String;
> > > ```
> > > !!
> > > ```
> > 
> > 
> > may be because of swift version difference...
> > what's your version about swift develop language?
> 
> 开发语言采用OC

* flutter plugin iOS: oc,swift,android:java,kotlin; please check your develop environment,and adapter it.

* such as support swift development language develop flutter project of your project
